### ISSUE TITLE
Randomization is different per timezone

### ISSUE THREAD

**Issue by mymakerofficial** [mymakerofficial/what-day-is-it#28]
I don't think that days should be different depending on where you live. I mean I don't think there are rules about this but it's my website so I make the rules. AND WHEN I SAY THAT EVERYBODY SHALL HAVE THE SAME DAY THEN EVERYBODY SHALL HAVE THE SAME DAY!

**Comment by stlenx** [comment]
Rude.

**Comment by mymakerofficial** [comment]
I'm sorry but I think day equality is very important.
